config/routes.rb
OttrApp::Application.routes.draw do
  resources :ideas
  resources :comments, :only => [:create]
  resources :invites, :only => [:update]
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="container">
Built at <a href="http://boston.startupweekend.org">Startup Weekend Boston</a>
</footer>

app/views/layouts/_header.html.erb
<header class="container">
	<% logo = image_tag("logo.png", :alt => "Sample App") %>
	<%= link_to logo, root_path %>
	
	<nav>
		<% if signed_in? %>
		<%= link_to "Float an Idea", new_idea_path, :class => "head_btn_shadow" %>
		<%= link_to "Float an Idea", new_idea_path, :class => "head_btn" %>
		<% else %>
		
			<div id="signup">
			<%= link_to "Sign up", user_omniauth_authorize_path(:facebook), :class => "head_btn_shadow" %>
			<%= link_to "Sign up", user_omniauth_authorize_path(:facebook), :class => "head_btn" %>
			</div>
		
		<% end %>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<link href='http://fonts.googleapis.com/css?family=Overlock:700italic,900italic' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
	<!-- The above Javascript is used to 'Fake' the DELETE request, 
		since Web Browsers cannot send DELETE requests natively -->
	<meta name="viewport" content="width=device-width; initial-scale=1.0" />
</head>
<body>
	<%= render 'layouts/header' %>

	<section>
		<% flash.each do |key, value| %>
			<div class="container"><%= content_tag(:div, value, :class => "flash #{key}") %></div>
		<% end %>
		<% if is_not_splashpage? %><div class="container"><% end %>
		<%= yield %>
		<% if is_not_splashpage? %></div><% end %>
		
	</section>

	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>